version: '3.5'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  web:
    image: docker-back-staging:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file: .env

  redis:
    image: redis
    command: redis-server
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=${REDIS_URL}
      - RAILS_ENV=${RAILS_ENV}

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    env_file: .env

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

volumes:
  postgres:
  redisdata:
  gem_cache:
  db_data:
  node_modules:
  minio_data:
