version: "3.5"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    restart: always

  redis:
    image: redis
    command: redis-server
    volumes:
      - ./tmp/redis:/data
    env_file:
      - ./.env
    restart: always

  sidekiq:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec sidekiq"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    restart: always

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    command: server --console-address ":9001" /data
    volumes:
      - ./tmp/minio:/data
    restart: always
