---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/canvas":
    get:
      summary: list canvas
      responses:
        '200':
          description: successful
    post:
      summary: create canva
      requestBody:
        $ref: '#/components/requestBodies/canvaBody'
      responses:
        '200':
          description: successful
  "/api/v1/canvas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show canva
      responses:
        '200':
          description: successful
    patch:
      summary: update canva
      requestBody:
        $ref: '#/components/requestBodies/canvaBody'
      responses:
        '200':
          description: successful
    put:
      summary: update canva
      requestBody:
        $ref: '#/components/requestBodies/canvaBody'
      responses:
        '200':
          description: successful
    delete:
      summary: delete canva
      responses:
        '200':
          description: successful
  "/api/v1/storiettes":
    get:
      summary: list storiettes
      responses:
        '200':
          description: successful
    post:
      summary: create storiette
      requestBody:
        $ref: '#/components/requestBodies/storietteBody'
      responses:
        '200':
          description: successful
  "/api/v1/storiettes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show storiette
      responses:
        '200':
          description: successful
    patch:
      summary: update storiette
      requestBody:
        $ref: '#/components/requestBodies/storietteBody'
      responses:
        '200':
          description: successful
    put:
      summary: update storiette
      requestBody:
        $ref: '#/components/requestBodies/storietteBody'
      responses:
        '200':
          description: successful
    delete:
      summary: delete storiette
      responses:
        '200':
          description: successful
  "/api/v1/chapters":
    get:
      summary: list chapters
      responses:
        '200':
          description: successful
    post:
      summary: create chapter
      requestBody:
        $ref: '#/components/requestBodies/chapterBody'
      responses:
        '200':
          description: successful
  "/api/v1/chapters/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show chapter
      responses:
        '200':
          description: successful
    patch:
      summary: update chapter
      requestBody:
        $ref: '#/components/requestBodies/chapterBody'
      responses:
        '200':
          description: successful
    put:
      summary: update chapter
      requestBody:
        $ref: '#/components/requestBodies/chapterBody'
      responses:
        '200':
          description: successful
    delete:
      summary: delete chapter
      responses:
        '200':
          description: successful
components:
  schemas:
    Canva:
      type: object
      required:
        - image
        - title
        - chapter_id
      properties:
        title:
          type: string
        image:
          type: string
          format: base64
        chapter_id:
          type: integer
    Storiette:
      type: object
      required:
        - image
        - title
        - description
    Chapter:
      type: object
      required:
        - title
        - description
        - storiette_id
  requestBodies:
    storietteBody:
      description: A JSON object containing storiette information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Storiette'
          example:
            storiette:
              title: Storiette number 1#
              description: "Storiette number 1"
    chapterBody:
      description: A JSON object containing chapter information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Chapter'
          example:
            chapter:
              title: Chapter number 1#
              description: "Chapter number 1"
              storiette_id: 1
    canvaBody:
      description: A JSON object containing canva information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/Canva'
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
