---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/canvas":
    get:
      summary: list canvas
      responses:
        '200':
          description: successful
    post:
      summary: create canva
      requestBody:
        $ref: '#/components/requestBodies/canvaBody'
      responses:
        '200':
          description: successful
  "/api/v1/canvas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show canva
      responses:
        '200':
          description: successful
    patch:
      summary: update canva
      requestBody:
        $ref: '#/components/requestBodies/canvaBody'
      responses:
        '200':
          description: successful
    put:
      summary: update canva
      requestBody:
        $ref: '#/components/requestBodies/canvaBody'
      responses:
        '200':
          description: successful
    delete:
      summary: delete canva
      responses:
        '200':
          description: successful
components:
  schemas:
    Canva:
      type: object
      required:
        - image
        - title
  requestBodies:
    canvaBody:
      description: A JSON object containing pet information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Canva'
          example:
            canva:
              title: Canva number 1#
              image: "{canva image json}"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
