default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DOCKER_DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: comic_api_development

test:
  <<: *default
  database: comic_api_test

production:
  <<: *default
  database: comic_api_production
